// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh99J6VaXoExsG91trjoJYAPHgeJxF04k',
    appId: '1:870880916736:web:2ca9a441e105f6967fefe5',
    messagingSenderId: '870880916736',
    projectId: 'f1-vision',
    authDomain: 'f1-vision.firebaseapp.com',
    storageBucket: 'f1-vision.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFd-ZEeoX8Iq25oASCig9joGdziD8HMtw',
    appId: '1:870880916736:android:5e594e6cea9c0c947fefe5',
    messagingSenderId: '870880916736',
    projectId: 'f1-vision',
    storageBucket: 'f1-vision.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsU3-gnhXU2s81SvPVkYVpXjJcj7aYh4E',
    appId: '1:870880916736:ios:bc32cb607f8daaec7fefe5',
    messagingSenderId: '870880916736',
    projectId: 'f1-vision',
    storageBucket: 'f1-vision.firebasestorage.app',
    iosClientId: '870880916736-4f2bakn7hinfutqhqgedd45kqvtej448.apps.googleusercontent.com',
    iosBundleId: 'com.example.f1Vision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsU3-gnhXU2s81SvPVkYVpXjJcj7aYh4E',
    appId: '1:870880916736:ios:bc32cb607f8daaec7fefe5',
    messagingSenderId: '870880916736',
    projectId: 'f1-vision',
    storageBucket: 'f1-vision.firebasestorage.app',
    iosClientId: '870880916736-4f2bakn7hinfutqhqgedd45kqvtej448.apps.googleusercontent.com',
    iosBundleId: 'com.example.f1Vision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh99J6VaXoExsG91trjoJYAPHgeJxF04k',
    appId: '1:870880916736:web:114657981ec53bb37fefe5',
    messagingSenderId: '870880916736',
    projectId: 'f1-vision',
    authDomain: 'f1-vision.firebaseapp.com',
    storageBucket: 'f1-vision.firebasestorage.app',
  );
}
